---
title: "Hong Kong Stock 4"
author: "Yeung Ka Ming, CFA"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../_posts") })
excerpt: "Stock Data"
layout: post
tags: Porfolio
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 150)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE, fig.width = 15)
```

# Summary
66 constituent stocks in Hang Seng Index. Stock prices
can be downloaded and plot by below.

## R Libraries
```{r}
library(quantmod)
library(tidyverse)
library(ggplot2)
```

## Preparation of data
```{r Setup environment, include=FALSE, cache=FALSE}
setwd("D:/OneDrive - The Chinese University of Hong Kong/GitHub/_source")
base_dir <- "D:/OneDrive - The Chinese University of Hong Kong/GitHub/" # i.e. where the jekyll blog is on the hard drive.
base_url <- "/" # keep as is
fig_path <- "images/" # put image to this path.

knitr::opts_knit$set(base.dir = base_dir, base.url = base_url)
knitr::opts_chunk$set(fig.path = fig_path,
                      message=FALSE, warning=FALSE,
                      cache = TRUE) 
```

Direct download by getSymbols
``` {r download stock data}
tickers <- c('0001.HK','0002.HK','0003.HK','0005.HK',
             '0006.HK','0011.HK','0012.HK','0016.HK',
             '0017.HK','0027.HK','0066.HK','0101.HK',
             '0175.HK','0241.HK','0267.HK','0288.HK',
             '0291.HK','0386.HK','0388.HK','0669.HK',
             '0688.HK','0700.HK','0762.HK','0823.HK',
             '0857.HK','0868.HK','0883.HK','0939.HK',
             '0941.HK','0960.HK','0968.HK','0992.HK',
             '1038.HK','1044.HK','1093.HK','1109.HK',
             '1113.HK','1177.HK','1211.HK','1299.HK',
             '1398.HK','1810.HK','1876.HK','1928.HK',
             '1997.HK','2007.HK','2018.HK','2020.HK',
             '2269.HK','2313.HK','2318.HK','2319.HK',
             '2331.HK','2382.HK','2388.HK','2628.HK',
             '2688.HK','3690.HK','3968.HK','3988.HK',
             '6098.HK','6862.HK','9618.HK','9633.HK',
             '9988.HK','9999.HK')
hkport <- new.env()
getSymbols(tickers, 
           env=hkport, 
           src = "yahoo",
           index.class = "POSIXct",
           from = "2022-01-01")
# auto.assign is FALSE, so an environment is used here. 
# Unlike US stocks, # the tickers in HK stock market is 
# by number, which cannot be the variable
# name in R. Further fine tune in next step.
```

## OHLC price
```{r OHLC}
head(Ad(hkport$`0001.HK`))
head(Cl(hkport$`0001.HK`))
head(Op(hkport$`0001.HK`))
head(Hi(hkport$`0001.HK`))
head(Lo(hkport$`0001.HK`))
```

## Prepare a dataframe with all adjusted close prices

Prepare dataframe
```{r prepare xts and tibble}
## To get all the adjusted close prices
## into a single xts object
ad.HSI.xts <- Reduce(merge,eapply(hkport, Ad))
colnames(ad.HSI.xts) <- sub('X','',colnames(ad.HSI.xts))

ad.HSI.tbl <- as_tibble(fortify(ad.HSI.xts))
ad.HSI.long.tbl <- ad.HSI.tbl %>% 
  pivot_longer(!Index,
               names_to = "tickers", 
               values_to = "Adjusted.Close")
ad.HSI.long.tbl
```

Plot graph
```{r adjusted close prices}
p3 <- ggplot(ad.HSI.long.tbl,
            aes(x = Index, 
                y = Adjusted.Close,
                color=tickers))
p3 + 
  geom_line(size = 1) + 
  xlab("Date") + 
  ylab("Adjusted Close")
```