---
title: "COVID-19 Confirmed Cases in Hong Kong"
author: "Yeung Ka Ming, CFA"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../_posts") })
excerpt: "COVID-19"
layout: post
tags: histogram
---
  
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 100)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE, fig.width = 10)
```

# Summary
COVID-19 confirmed cases by age and gender in Hong Kong 

## R Libraries
```{r}
library(ggplot2)
library(tidyverse)
```

## Preparation of data
Download data from WHO website
```{r Setup environment, include=FALSE, cache=FALSE}
setwd("D:/OneDrive - The Chinese University of Hong Kong/GitHub/_source")
base_dir <- "D:/OneDrive - The Chinese University of Hong Kong/GitHub/" # i.e. where the jekyll blog is on the hard drive.
base_url <- "/" # keep as is
fig_path <- "images/" # customize to heart's content, I 'spose.

knitr::opts_knit$set(base.dir = base_dir, base.url = base_url)
knitr::opts_chunk$set(fig.path = fig_path,
                      message=FALSE, warning=FALSE,
                      cache = TRUE) 
```

```{r import data}
enhanced_sur_covid_19_eng <- read.csv("d:/Users/ivan/Downloads/enhanced_sur_covid_19_eng.csv")
```

```{r}
hkcovid.tbl <- as_tibble(enhanced_sur_covid_19_eng)

hkcovid1.tbl <- hkcovid.tbl %>% 
  mutate(Report.date = as.Date(Report.date, format = "%d/%m/%Y"), 
         Date.of.onset = as.Date(Date.of.onset, format = "%d/%m/%Y"))
```

## Simple plot date vs confirmed cases
```{r simple plot date vs confirmed cases}
hkcovid1.tbl %>% 
  group_by(Report.date) %>% 
  summarise(n = n()) %>% 
  plot(type = "l")
```

## date vs gender
```{r ggplot date vs gender}
hkcovid2.tbl <- hkcovid1.tbl %>%
  group_by(Report.date, Gender) %>%
  summarise(n = n())
p <- ggplot(hkcovid2.tbl, aes(x=Report.date, y=n, color=Gender))
p+geom_line()

hkcovid2.tbl <- hkcovid1.tbl %>%
  group_by(Report.date, Gender) %>% 
  filter(Gender == 'M' | Gender == 'F') %>% 
  summarise(n = n())
p1 <- ggplot(hkcovid2.tbl, aes(x=Report.date, y=n, color=Gender))
p1+geom_line(aes(linetype=Gender))+scale_size_manual(values=c(2, 2.5))
```

## histogram
```{r histogram}
hkcovid3.tbl <- hkcovid1.tbl %>% 
  group_by(Age,Gender) %>% 
  filter(Gender == 'M' | Gender == 'F')
hkcovid4.tbl <- hkcovid3.tbl %>% 
  mutate(Age = as.integer(Age))
p2 <- ggplot(hkcovid4.tbl, 
            aes(x=Age, color=Gender, fill=Gender)) + 
  geom_histogram(binwidth=1, color="Black", position="identity", alpha=0.25)
p2

p3 <- ggplot(hkcovid4.tbl,
             aes(x=Age, color=Gender, fill=Gender)) + 
  geom_histogram(binwidth=1, 
                 color="Black", 
                 position="identity", 
                 alpha=0.25,
                 aes(y=..density..)) + 
  geom_density(alpha=.2, fill="#FF6666")
p3
```