---
title: "Bollinger Bands"
author: "Yeung Ka Ming, CFA"
date: "`r Sys.Date()`"
output:
  md_document:
  variant: gfm
preserve_yaml: TRUE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../_posts") })
excerpt: "Technical Analysis"
layout: post
tags: BollingerBands
---

```{r set-options, echo=FALSE, cache=FALSE}
options(width = 100)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE, fig.width = 10)
```

# Summary
Bollinger Bands

## R Libraries
```{r library}
library(quantmod)
library(TTR)
```

## Preparation of data
```{r Setup environment, include=FALSE, cache=FALSE}
setwd("D:/OneDrive - The Chinese University of Hong Kong/GitHub/_source")
base_dir <- "D:/OneDrive - The Chinese University of Hong Kong/GitHub/" # i.e. where the jekyll blog is on the hard drive.
base_url <- "/" # keep as is
fig_path <- "images/" # customize to heart's content, I 'spose.

knitr::opts_knit$set(base.dir = base_dir, base.url = base_url)
knitr::opts_chunk$set(fig.path = fig_path,
                      message=FALSE, warning=FALSE,
                      cache = TRUE) 
```

```{r download data}
tickers <- c("^HSI","^GSPC")
getSymbols(Symbols = tickers,
           src = "yahoo",
           index.class = "POSIXct",
           from = "1997-01-01")
```

## Prepare technical analysis of Bollinger Bands
```{r bollinger bands}
bbands.HLC <- BBands(na.omit(HSI[,c("HSI.High","HSI.Low","HSI.Close")]))
```

## Plot
```{r BBands plot}
plot(bbands.HLC)
plot(bbands.HLC["2020/2022"])
plot(bbands.HLC["2020/2022"][,1:3])
plot(bbands.HLC["2020/2022"][,4])
```