---
title: "Hong Kong Stock 5"
author: "Yeung Ka Ming, CFA"
date: "`r Sys.Date()`"
output:
  md_document:
    variant: gfm
    preserve_yaml: TRUE
knit: (function(inputFile, encoding) {
  rmarkdown::render(inputFile, encoding = encoding, output_dir = "../_posts") })
excerpt: "OOCL"
layout: post
tags: Portfolio
---
```{r set-options, echo=FALSE, cache=FALSE}
options(width = 150)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, error = FALSE, message = FALSE, fig.width = 15)
```

# Summary
OOCL is a shipping company and the performance during the pandemic is extraordinary.

## R Libraries
```{r}
library(quantmod)
library(tidyverse)
library(ggplot2)
```

## Preparation of data
```{r Setup environment, include=FALSE, cache=FALSE}
setwd("D:/OneDrive - The Chinese University of Hong Kong/GitHub/_source")
base_dir <- "D:/OneDrive - The Chinese University of Hong Kong/GitHub/" # i.e. where the jekyll blog is on the hard drive.
base_url <- "/" # keep as is
fig_path <- "images/" # put image to this path.

knitr::opts_knit$set(base.dir = base_dir, base.url = base_url)
knitr::opts_chunk$set(fig.path = fig_path,
                      message=FALSE, warning=FALSE,
                      cache = TRUE) 
```

Direct download by getSymbols
``` {r download stock data}
tickers <- c('0316.HK','2800.HK')
hkport <- new.env()
getSymbols(tickers, 
           env=hkport, 
           src = "yahoo",
           index.class = "POSIXct",
           from = "2020-01-01")
# auto.assign is FALSE, so an environment is used here. 
# Unlike US stocks, # the tickers in HK stock market is 
# by number, which cannot be the variable
# name in R. Further fine tune in next step.
```

## OHLC price
```{r OHLC}
head(Ad(hkport$`0316.HK`))
head(Cl(hkport$`0316.HK`))
head(Op(hkport$`0316.HK`))
head(Hi(hkport$`0316.HK`))
head(Lo(hkport$`0316.HK`))
```

## Prepare a dataframe with all adjusted close prices

Prepare dataframe
```{r prepare xts and tibble}
## To get all the close prices
## into a single xts object
cl.stocks.xts <- Reduce(merge,eapply(hkport, Cl))
colnames(cl.stocks.xts) <- sub('X','',colnames(cl.stocks.xts))

cl.stocks.tbl <- as_tibble(fortify(cl.stocks.xts))
cl.stocks.long.tbl <- cl.stocks.tbl %>% 
  pivot_longer(!Index,
               names_to = "tickers", 
               values_to = "Close.Prices")
cl.stocks.long.tbl
```

Plot graph
```{r adjusted close prices}
p4 <- ggplot(cl.stocks.long.tbl,
            aes(x = Index, 
                y = Close.Prices,
                color=tickers))
p4 + 
  geom_line(size = 1) + 
  xlab("Date") + 
  ylab("Close Prices")
```